version: '3'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./artifacts/init_db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
